name: CI/CD para Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Obtener c칩digo fuente
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar migraciones Django
      run: |
        python manage.py migrate

    - name: Recolectar archivos est치ticos
      run: |
        python manage.py collectstatic --noinput

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: producci칩n
      url: foslatinos.azurewebsites.net

    steps:
    - name: Desplegar en Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: FosLatinos
        slot-name: producci칩n
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
